travis:
  secure:
    BINSTAR_TOKEN: R70FICbl1ET/OqTPKTImml1fWOnFatwdOfbHP2WVDZ4aCIYfX1AHF7h1jTgOnIL0IZ8/muqeexTREtJNxFBpVitFS13N5MKtNPzmCfIS7VF3Y2Q1FKTPoLEOJnHv0KAOE68ZOv1ms6BWi0S/8LjM/LdAakgFUK8lW5u0ErFwtbyIF7ZD/u+mTUU9mAXQ4pIUIL0ZIIKeaT75N/CuWbCeEO1qN8D9CJvasO7OrXwtFqiRmCLBDKox0EtM63DTlWPkJCfT7LtRZlpt7utsDmWP3GSmrCzTElcridD2bOTyqDqb2NmAdvjuxbLGiOTWMEOQTcx3cFCV/THWvAuCLZu3MCp1P2dE4AwimnsGVBnn6AuP/JnxQWmFKiBttrxxad75srrA9rG+ZMw52tTnJ0W+B8zTkluqBs4oSIE1fUk5DtTMIXKa6G5bo2B3HfuSkF6lS9Mzg7DshXk48C7ti4xTni9o0koQQAOGvXSNvlEN6DBqlxf1KYyp2ntFyreLrajufolbP3jqmI3yR/T6XeM+QwKv+njmzAxAaR7mQ2m/fgegIydte94UBgekTY66qJIVYpyqddggb1iT7Hqo3YmaVSTaj0xL+QmSVAO1ozdy+qNi5IUcRx8dpkQ5wTALuyPz+M2qNmpyxLFLSdZRZyAbyvQ9tpySoA+WABJ0v0iAk+A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
